// Code generated by "stringer -type=tokenKind -linecomment"; DO NOT EDIT.

package parser

import "strconv"

const _tokenKind_name = "tokenUnknownEOFIDENTSTRING_tokStartKeywordsSELECTSENDSHAREACCOUNTFROMTOWITHWHEREANDSETDATA_tokEndKeywordsNUMBERCOMMAEQUALQUOTES"

var _tokenKind_index = [...]uint8{0, 12, 15, 20, 26, 43, 49, 53, 58, 65, 69, 71, 75, 80, 83, 86, 90, 105, 111, 116, 121, 127}

func (i tokenKind) String() string {
	if i < 0 || i >= tokenKind(len(_tokenKind_index)-1) {
		return "tokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenKind_name[_tokenKind_index[i]:_tokenKind_index[i+1]]
}
