// Code generated by "stringer -type=tokenKind -linecomment"; DO NOT EDIT.

package parser

import "strconv"

const _tokenKind_name = "tokenUnknowntokenEofIDENT_tokStartKeywordsSELECTSENDSHAREACCOUNTFROMTOWITHWHEREAND_tokEndKeywordsNUMBERCOMMA"

var _tokenKind_index = [...]uint8{0, 12, 20, 25, 42, 48, 52, 57, 64, 68, 70, 74, 79, 82, 97, 103, 108}

func (i tokenKind) String() string {
	if i < 0 || i >= tokenKind(len(_tokenKind_index)-1) {
		return "tokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenKind_name[_tokenKind_index[i]:_tokenKind_index[i+1]]
}
