// Code generated by "stringer -type=tokenKind -linecomment"; DO NOT EDIT.

package parser

import "strconv"

const _tokenKind_name = "tokenUnknowntokenEofIDENTSELECTSENDFROMTOWITHWHERENUMBERCOMMA"

var _tokenKind_index = [...]uint8{0, 12, 20, 25, 31, 35, 39, 41, 45, 50, 56, 61}

func (i tokenKind) String() string {
	if i < 0 || i >= tokenKind(len(_tokenKind_index)-1) {
		return "tokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenKind_name[_tokenKind_index[i]:_tokenKind_index[i+1]]
}
